import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { useEffect, useState } from 'react'
import { PrismaClient } from '@prisma/client'

console.log("This one gets called on both client and server side")


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [fruits, setFruits] = useState([])
  const handleSubmit = async (e) => {
    e.preventDefault()
    const res = await axios.post('/api/fruits', { name, color })
    // setFruits([...fruits, res.data])
    console.log({name, color})}
  // 1 way of doing the same thing
  // useEffect(()=>{
  //   (async () => {
  //     const fruits = await axios.get("/api/fruits")
  //     setFruits(fruits.data)
  //   })()
  // }, [])

  //another way of doing the same thing
  //this one gets called only on the server side
  useEffect(()=> {
    axios.get("/api/fruits")
    .then(fruits =>
      setFruits(fruits.data))
  }, [])

  const [name, setName] = useState('')
  const [color, setColor] = useState('')

  return (
    <>
      <Head>
        <title>Fruity</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.header}>
        <form onSubmit={handleSubmit} style={{display: "flex", flexDirection: "column", maxWidth: "400px"}}>
                <input type="text" value={name} onChange={(e) => setName(e.target.value)} />
                <textarea value={color} onChange={(e) => setColor(e.target.value)} />
                <button type="submit">Submit</button>
            </form>
          <ul>
            {fruits.map((fruit)=>{
              <li key={fruit.id}>{fruit.name} is {fruit.color}</li>
            })}
          </ul>
        </h1>
      </main>
    </>
  )
}


// export async function getServerSideProps(){
//   const prisma = new PrismaClient;
//   console.log("This gets called")
//   return {
//     props: {
//       fruits: JSON.parse(JSON.stringify(fruits))
//     }
//   }
// }